require_relative 'generators/domain'
require_relative 'generators/entity'
require_relative 'generators/root'
require_relative 'generators/value_object'
require_relative 'generators/operation'
require_relative 'generators/domain_files'
require_relative 'generators/spec'
