require 'singleton'
require_relative 'hecks_domain/repository'
require_relative 'hecks_domain/support/string'
require_relative 'hecks_domain/events'
require_relative 'hecks_domain/commands'
require_relative 'hecks_domain/factories'
require_relative 'hecks_domain/invariants/invariant_loader'
